# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-07-18 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
