# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-08-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190803_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='1'),
        ),
    ]
